# Generated by Django 3.0.4 on 2022-04-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilesActions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
