# Generated by Django 3.2.13 on 2022-06-16 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilesActions', '0004_auto_20220616_0452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='messages',
        ),
    ]
