# Generated by Django 3.2.13 on 2022-06-16 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilesActions', '0006_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='sender',
        ),
    ]
