# Generated by Django 4.0.4 on 2022-05-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20220511_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='preview',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='thanks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
