# Generated by Django 3.0.4 on 2022-03-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20220327_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='mobile',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='specialize',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
