# Generated by Django 4.0.4 on 2022-05-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_doctors_preview_doctors_thanks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='preview',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='thanks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
