# Generated by Django 4.0.4 on 2022-05-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_topics_date_alter_doctors_preview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='preview',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='thanks',
        ),
    ]
