# Generated by Django 4.0.4 on 2022-05-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_doctors_preview_remove_doctors_thanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_mobile_verified',
            field=models.BooleanField(default=False),
        ),
    ]
