# Generated by Django 4.0.4 on 2022-05-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_customuser_is_mobile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='accept_insurance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='insurance_companies',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
