# Generated by Django 4.0.4 on 2022-05-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_doctors_accept_insurance_doctors_insurance_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='previews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='thanks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
