# Generated by Django 3.0.4 on 2022-03-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20220330_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='dataOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='blood',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='dataOfBirth',
            field=models.DateField(null=True),
        ),
    ]
