# Generated by Django 4.0.4 on 2022-05-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_doctors_previews_doctors_thanks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='insurance_companies',
            new_name='insurance_company1',
        ),
        migrations.AddField(
            model_name='doctors',
            name='insurance_company2',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='insurance_company3',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
