# Generated by Django 3.0.4 on 2022-03-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20220330_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='dataOfBirth',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
