# Generated by Django 3.0.4 on 2022-03-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_auto_20220330_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='dataOfBirth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='dataOfBirth',
            new_name='dateOfBirth',
        ),
    ]
