# Generated by Django 3.0.4 on 2022-03-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_auto_20220330_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='dateOfBirth',
            new_name='dateofbirth',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='dateOfBirth',
            new_name='dateofbirth',
        ),
    ]
