# Generated by Django 3.0.4 on 2022-03-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_auto_20220330_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='mobile',
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
