# Generated by Django 3.0.4 on 2022-03-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_auto_20220330_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
