# Generated by Django 3.0.4 on 2022-04-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_auto_20220330_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='district',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='district',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='heigh',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='weight',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
