# Generated by Django 3.0.4 on 2022-04-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_auto_20220403_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=40, unique=True, verbose_name='username'),
        ),
    ]
