# Generated by Django 3.0.4 on 2022-04-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_auto_20220418_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='image',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='image',
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
