# Generated by Django 3.0.4 on 2022-04-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_auto_20220419_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='default-avatar.jpg', null=True, upload_to='image'),
        ),
    ]
