# Generated by Django 3.0.4 on 2022-04-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_auto_20220422_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
