# Generated by Django 3.0.4 on 2022-04-29 16:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_auto_20220422_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='profile_pic'),
            preserve_default=False,
        ),
    ]
