# Generated by Django 4.0.4 on 2022-05-18 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_doctors_preview_remove_doctors_thanks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PatientActions', '0003_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.IntegerField(blank=True, default=0, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Previews', to='Users.doctors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Previews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preview',
                'verbose_name_plural': 'Previews',
            },
        ),
        migrations.CreateModel(
            name='Thanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thanks', models.IntegerField(blank=True, default=0, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Thanks', to='Users.doctors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Thanks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thank',
                'verbose_name_plural': 'Thanks',
            },
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
