# Generated by Django 3.0.4 on 2022-04-24 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_auto_20220422_1449'),
        ('PatientActions', '0004_auto_20220424_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='user',
        ),
        migrations.AddField(
            model_name='reservations',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Users.Patients'),
            preserve_default=False,
        ),
    ]
