# Generated by Django 3.0.4 on 2022-04-24 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PatientActions', '0005_auto_20220424_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='patient',
        ),
        migrations.AddField(
            model_name='reservations',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
