# Generated by Django 3.0.4 on 2022-04-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientActions', '0007_auto_20220425_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='date',
            new_name='createdate',
        ),
    ]
