# Generated by Django 3.0.4 on 2022-04-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientActions', '0008_auto_20220425_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='opptdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
