# Generated by Django 3.0.4 on 2022-05-11 00:10

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='clinic_image')),
                ('clinicname', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('workhours', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('district', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'verbose_name': 'Clinic',
                'verbose_name_plural': 'Clinics',
            },
        ),
    ]
