# Generated by Django 4.0.4 on 2022-05-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorActions', '0002_clinics_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinics',
            name='clinicname',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
